name: PR Approve

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/pr-approve@main
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            HI @${{ github.event.pull_request.user.login }}, approve
